-- 1. Create table for User Progress (Last page, last file)
create table user_progress (
  user_id uuid references auth.users not null primary key,
  last_file text,
  last_content text,
  last_page int,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Security (RLS)
alter table user_progress enable row level security;

-- Allow users to read/write only their own data
create policy "Users can manage own progress" on user_progress
  for all using (auth.uid() = user_id);


-- 2. Create table for Word Stats (Correct/Wrong counts)
create table user_stats (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  word text not null,
  correct int default 0,
  wrong int default 0,
  last_practiced bigint,
  constraint unique_user_word unique (user_id, word)
);

-- Enable Security (RLS)
alter table user_stats enable row level security;

-- Allow users to read/write only their own stats
create policy "Users can manage own stats" on user_stats
  for all using (auth.uid() = user_id);
